### ISSUE TITLE
失效了好像

### ISSUE THREAD

**Issue by xiaop-coder** [Y5neKO/huluxia_auto_comment#2]
PS C:\Users\xiaop\Desktop\huluxia_auto_comment-main> python main_2.0.py
Traceback (most recent call last):
  File "C:\Users\xiaop\Desktop\huluxia_auto_comment-main\main_2.0.py", line 201, in <module>
    main()
  File "C:\Users\xiaop\Desktop\huluxia_auto_comment-main\main_2.0.py", line 114, in main
    post_id = get_post_id()
              ^^^^^^^^^^^^^
  File "C:\Users\xiaop\Desktop\huluxia_auto_comment-main\main_2.0.py", line 32, in get_post_id
    id_2 = random.randint(1, lines)  # 随机获取行数
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiaop\AppData\Local\Programs\Python\Python312\Lib\random.py", line 336, in randint
    return self.randrange(a, b+1)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiaop\AppData\Local\Programs\Python\Python312\Lib\random.py", line 319, in randrange
    raise ValueError(f"empty range in randrange({start}, {stop})")
ValueError: empty range in randrange(1, 1)

**Comment by Y5neKO** [comment]
这个是几年前写的东西了，现在hlx加了一些反爬机制，所以已经不能用了，有兴趣的话可以等我有空看看能不能更新一下

**Comment by xiaop-coder** [comment]
> 这个是几年前写的东西了，现在hlx加了一些反爬机制，所以已经不能用了，有兴趣的话可以等我有空看看能不能更新一下

好的👌🏻
